fix: Remove use of Block.getName() to stop server crash
getName() is only used to print the name of the removed block. No
need to do that anymore. I'm surprised this isn't available on the
server. Need to figure out what the specific rules are determining
its existence.

net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:851)
	at net.minecraft.class_3176.method_3813(class_3176.java:343)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:654)
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_2248.method_9518()'
	at net.minecraft.class_2404.maybeErodeEdge(class_2404.java:619)
	at net.minecraft.class_2404.handler$zce000$randomTick(class_2404.java:592)